<div id="menu">
	<a class="menuItem" href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'index')); ?>">Articulos</a> <br>
	<a class="menuItem" href="<?php echo $this->url(array('controller' => 'students', 'action' => 'index')); ?>">Estudiantes</a> <br>
	<a class="menuItem" href="<?php echo $this->url(array('controller' => 'projects', 'action' => 'index')); ?>">Proyectos</a> <br>
	<a class="menuItem" href="<?php echo $this->url(array('controller' => 'visitors', 'action' => 'index')); ?>">Visitantes</a> <br>
	<a class="menuItem" href="<?php echo $this->url(array('controller' => 'activities', 'action' => 'index')); ?>">Actividades</a> <br>
</div>
