<br /><br />
<div id="view-content">
	<a href="<?php echo $this->url(array('controller' => 'articles', 'action' => 'index')); ?>">Articulos</a> <br>
	<a href="<?php echo $this->url(array('controller' => 'students', 'action' => 'index')); ?>">Estudiantes</a> <br>
	<a href="<?php echo $this->url(array('controller' => 'projects', 'action' => 'index')); ?>">Proyectos</a> <br>
<!-- 	<a href="/gds/public/index/groups">Grupos</a> -->
	<a href="<?php echo $this->url(array('controller' => 'visitors', 'action' => 'index')); ?>">Visitantes</a> <br>
</div>
