<br /><br />
<div id="view-content">
	<a href="<?php echo $this->url(array('controller' => 'articles')); ?>">Articulos</a> <br>
	<a href="<?php echo $this->url(array('controller' => 'students')); ?>">Estudiantes</a> <br>
	<a href="<?php echo $this->url(array('controller' => 'projects')); ?>">Proyectos</a> <br>
<!-- 	<a href="/gds/public/index/groups">Grupos</a> -->
	<a href="<?php echo $this->url(array('controller' => 'visitors')); ?>">Visitantes</a> <br>
</div>
