#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
The same code must be used in authors.py fullnames.py and groups.py
"""
groups={}
groups['001']='GMC: Grupo de Materia Condensada'
groups['002']='GMC: Grupo de Materia Condensada'
groups['003']='GMC: Grupo de Materia Condensada'
groups['004']='GMC: Grupo de Materia Condensada'
groups['005']='GMC: Grupo de Materia Condensada'
groups['006']='GMC: Grupo de Materia Condensada'
groups['007']='GMC: Grupo de Materia Condensada'
groups['100']='FACOM: Física y Astrofísica Computacional'
groups['101']='FACOM: Física y Astrofísica Computacional'
groups['102']='FACOM: Física y Astrofísica Computacional'
groups['103']='FACOM: Física y Astrofísica Computacional'
groups['104']='FACOM: Física y Astrofísica Computacional'
groups['105']='FACOM: Física y Astrofísica Computacional'
groups['200']='GFAM: Grupo de Física Atómica y Molecular'
groups['201']='GFAM: Grupo de Física Atómica y Molecular'
groups['202']='GFAM: Grupo de Física Atómica y Molecular'
groups['202']='GFAM: Grupo de Física Atómica y Molecular'
groups['203']='GFAM: Grupo de Física Atómica y Molecular'
groups['204']='GFAM: Grupo de Física Atómica y Molecular'
groups['300']='MS: Magnetismo y Simulación'
groups['301']='MS: Magnetismo y Simulación'
groups['302']='MS: Magnetismo y Simulación'
groups['303']='MS: Magnetismo y Simulación'
groups['304']='MS: Magnetismo y Simulación'
groups['305']='MS: Magnetismo y Simulación'
groups['400']='GICM: Grupo de Instrumentación Científica y Microelectrónica'
groups['401']='GICM: Grupo de Instrumentación Científica y Microelectrónica'
groups['402']='GICM: Grupo de Instrumentación Científica y Microelectrónica'
groups['500']='GES: Estado Sólido'
groups['501']='GES: Estado Sólido'
groups['502']='GES: Estado Sólido'
groups['503']='GES: Estado Sólido'
groups['504']='GES: Estado Sólido'
groups['505']='GES: Estado Sólido'
groups['506']='GES: Estado Sólido'
groups['507']='GES: Estado Sólido'
groups['508']='GES: Estado Sólido'
groups['509']='GES: Estado Sólido'
groups['510']='GES: Estado Sólido'
groups['600']='GOF: Grupo Óptica y Fotónica'
groups['601']='GOF: Grupo Óptica y Fotónica'
groups['602']='GOF: Grupo Óptica y Fotónica'
groups['603']='GOF: Grupo Óptica y Fotónica'
groups['604']='GOF: Grupo Óptica y Fotónica'
groups['605']='GOF: Grupo Óptica y Fotónica'
groups['701']='GFIF: Grupo de Fenomenología de Interacciones Fundamentales'
groups['702']='GFIF: Grupo de Fenomenología de Interacciones Fundamentales'
groups['703']='GFIF: Grupo de Fenomenología de Interacciones Fundamentales'
groups['704']='GFIF: Grupo de Fenomenología de Interacciones Fundamentales'
groups['705']='GFIF: Grupo de Fenomenología de Interacciones Fundamentales'
groups['706']='GFIF: Grupo de Fenomenología de Interacciones Fundamentales'
groups['707']='GFIF: Grupo de Fenomenología de Interacciones Fundamentales'
groups['708']='GFIF: Grupo de Fenomenología de Interacciones Fundamentales'
groups['709']='GFIF: Grupo de Fenomenología de Interacciones Fundamentales'
groups['800']='Biofísica'
groups['801']='Biofísica'
groups['802']='Biofísica'
groups['803']='Biofísica'
groups['900']='FN: Física Nuclear'
groups['901']='FN: Física Nuclear'
groups['902']='FN: Física Nuclear'
groups['903']='FN: Física Nuclear'
groups['1000']='FIR: Física Industrial y de la Radiación'
groups['1001']='FIR: Física Industrial y de la Radiación'


