<?php
$this->headLink()->appendStylesheet($this->baseUrl().'/css/global.css');
$this->headScript()->appendFile($this->baseUrl().'/js/json.js');
echo $this->doctype("HTML5");
?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <script type="text/javascript" src="<?php echo $this->baseUrl()."/js/jquery/jquery.js"; ?>"></script>
  <?php
    echo $this->headMeta();
    echo $this->headScript();
    echo $this->headLink();
    $this->headTitle()->prepend('GfifDev - ');
    echo $this->headTitle();
  ?>
</head>
<body>
  <header><h1><span id="zf-name">GDS Instituto de Física</span></h1></header>
  <table class="bodyPage">
    <tr>
    <td class="menu" width="20%">
      <?php echo $this->render('index/menu.phtml'); ?>
    </td>
    <td id="content" class="content" width="80%">
      <?php echo $this->layout()->content; ?>
    </td>
    </tr>
  </table>
  <footer><h1><span id="zf-name">Gfif Development Team</span></h1></footer>
</body>
</html>