<?php
$this->headLink()->appendStylesheet($this->baseUrl().'/css/global.css');
$this->headScript()->appendFile($this->baseUrl().'/js/json.js');
echo $this->doctype()
?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <script type="text/javascript" src="<?php echo $this->baseUrl()."/js/jquery/jquery.js"; ?>"></script>
  <?php
    echo $this->headMeta();
    echo $this->headScript();
    echo $this->headLink();
    $this->headTitle()->prepend('GfifDev - ');
    echo $this->headTitle();
  ?>
</head>
<body>
  <table class="bodyPage">
    <tr>
      <td class="header" colspan="2">
        <h1><span id="zf-name">GDS Instituto de Física</span></h1> 
      </td>
    </tr>
    <tr>
      <td class="menu" width="20%">
          <?php echo $this->render('index/menu.phtml'); ?>
      </td>
      <td class="content" width="80%">
         <div id="content"><?php echo $this->layout()->content ?></div>
      </td>
    </tr>
    <tr>
      <td class="footpage" colspan="2">
        <h1><span id="zf-name">Gfif Development Team</span></h1>     
      </td>
    </tr>
  </table>
<div id="debug"></div>
</body>
</html>
