<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>GDS</title>
  <?php echo $this->headLink()->appendStylesheet('/gds/css/global.css');
	echo $this->headScript()->appendFile('/gds/js/json.js');
?>

</head>
<body>

<div style="height:500px;width:100%" >
  <div id="header" style="height:15%;width:100%" >
    <h1><span id="zf-name">GDS Instituto de Física</span></h1> 
  </div>
  <div id="menu" style="height:100%;width:20%;float:left;">
         <?php echo $this->render('index/menu.phtml'); ?>
  </div>
  <div id="content" style="height:100%;width:78%;float:right">
        <?php echo $this->layout()->content ?>
  </div>
  <div id="footpage" style="height:10%;width:100%;clear:both">
 <h1><span id="zf-name">Gfif Development Team</span></h1>     

  </div>
</div>


</body>
</html>
